version: '3.4'

services:
  mysql:
    container_name: threads-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: threads
      MYSQL_DATABASE: threads
      MYSQL_USER: threads
      MYSQL_PASSWORD: threads
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
